'use client';
import { useCallback,useEffect,useState } from 'react';
import { io } from 'socket.io-client';
import { BellRing,Command,RefreshCw,Send,Terminal } from 'lucide-react';
import PageHeader from '../../../components/PageHeader';
import StatusBadge from '../../../components/StatusBadge';
import { ErrorState,LoadingState } from '../../../components/States';
import { request,session,SOCKET_URL } from '../../../services/api';
import { machines as loadMachines } from '../../../services/machine.service';

export default function CommandsPage(){
 const [commands,setCommands]=useState([]),[machines,setMachines]=useState([]),[machineId,setMachineId]=useState(''),[sending,setSending]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [commandResult,machineResult]=await Promise.all([request('/commands'),loadMachines()]);setCommands(commandResult||[]);setMachines(machineResult.data||[]);setMachineId(current=>current||machineResult.data?.[0]?.id||'')}catch(loadError){setError(loadError.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 useEffect(()=>{const token=session()?.accessToken;if(!token||!machines.length)return;const socket=io(SOCKET_URL,{auth:{token},transports:['websocket','polling']});socket.on('connect',()=>machines.forEach(machine=>socket.emit('machine:join',machine.id)));socket.on('command:updated',updated=>setCommands(current=>{const exists=current.some(command=>command.id===updated.id);return exists?current.map(command=>command.id===updated.id?{...command,...updated}:command):[updated,...current]}));return()=>socket.close()},[machines.map(machine=>machine.id).join(',')]);
 async function send(type){if(!machineId)return;setSending(type);setError('');try{const payload=type==='BEEP'?{type,payload:{durationMs:500}}:{type};const result=await request(`/commands/machines/${machineId}`,{method:'POST',body:JSON.stringify(payload)});setCommands(current=>[result,...current.filter(command=>command.id!==result.id)])}catch(sendError){setError(sendError.message)}finally{setSending('')}}
 if(loading)return <div className="admin-page"><LoadingState label="Carregando canal de comandos..."/></div>;
 return <div className="admin-page"><PageHeader eyebrow="CANAL MQTT SEGURO" title="Comandos remotos" description="Envie ações não críticas e acompanhe o ACK retornado pelo ESP32."/>{error&&<ErrorState message={error} onRetry={load}/>}<section className="surface-panel command-console"><div className="command-target"><label><span>ESCAVADEIRA DE DESTINO</span><select value={machineId} onChange={event=>setMachineId(event.target.value)}>{machines.map(machine=><option value={machine.id} key={machine.id}>{machine.code} · {machine.name}</option>)}</select></label><div><button onClick={()=>send('REQUEST_STATUS')} disabled={!!sending}><RefreshCw size={16}/>{sending==='REQUEST_STATUS'?'ENVIANDO...':'SOLICITAR STATUS'}</button><button className="accent" onClick={()=>send('BEEP')} disabled={!!sending}><BellRing size={16}/>{sending==='BEEP'?'ENVIANDO...':'TESTAR BUZZER'}</button></div></div><p className="command-safety"><Terminal size={15}/> Comandos de corte, partida e relé permanecem bloqueados no servidor e no firmware.</p></section><section className="surface-panel command-history"><div className="panel-header"><div><span className="eyebrow">RASTREAMENTO DE ACK</span><h2>Histórico recente</h2></div><Command size={19}/></div><div className="responsive-table"><table><thead><tr><th>MÁQUINA</th><th>COMANDO</th><th>STATUS</th><th>CRIADO</th><th>ÚLTIMO EVENTO</th></tr></thead><tbody>{commands.map(command=><tr key={command.id}><td><b>{command.machine?.code||'—'}</b></td><td><span className="command-type"><Send size={12}/>{command.type}</span></td><td><StatusBadge status={command.status}/></td><td>{formatDate(command.createdAt)}</td><td>{command.events?.[0]?`${command.events[0].status} · ${formatDate(command.events[0].createdAt)}`:'Aguardando ACK'}</td></tr>)}</tbody></table></div></section></div>
}
function formatDate(value){return value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—'}
