ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TABLE "Company" ADD COLUMN "logoData" TEXT;
ALTER TABLE "Company" ADD COLUMN "accentColor" VARCHAR(7);
ALTER TABLE "User" ADD COLUMN "avatarData" TEXT;
