import { Router } from 'express';
import { authController } from './auth.controller.js';
import { validate } from '../../middlewares/validation.middleware.js';
import { authenticate } from '../../middlewares/auth.middleware.js';
import { loginSchema, refreshSchema, profileSchema, changePasswordSchema } from './auth.validation.js';
export const authRouter = Router();
authRouter.post('/login', validate(loginSchema), authController.login);
authRouter.post('/refresh', validate(refreshSchema), authController.refresh);
authRouter.post('/logout', authController.logout);
authRouter.get('/me', authenticate, authController.me);
authRouter.patch('/me', authenticate, validate(profileSchema), authController.updateMe);
authRouter.post('/change-password', authenticate, validate(changePasswordSchema), authController.changePassword);
