ALTER TABLE "MachineCurrentState"
ADD COLUMN "gpsValid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "gpsUpdatedAt" TIMESTAMP(3),
ADD COLUMN "rfidCode" TEXT,
ADD COLUMN "rfidStatus" TEXT NOT NULL DEFAULT 'AWAITING_CARD',
ADD COLUMN "deviceBootId" TEXT;
